### ISSUE TITLE
Failed to open device

### ISSUE THREAD

**Issue by akshit-sharma** [LiljebergXYZ/steelseries-arctis-7-battery#1]
Hey, I am trying to use this program on Ubuntu 20.04. I have not worked with rust before.
I am running the following command to compile and run the executable:
```cargo build && ./target/debug/steelseries-arctis-seven```
Which gives me the following error:
```
thread 'main' panicked at 'Failed to open device: OpenHidDeviceError', src/main.rs:8:44
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Looking at the line number, it is failing at:
```let headset = api.open(0x1038, 0x12ad).expect("Failed to open device");```

I used lsusb to check for  the ID of the device connect and one of the row contained:
```Bus 001 Device 014: ID 1038:12ad SteelSeries ApS```

Is there a way to fix this error?

**Comment by faejr** [comment]
Hello!

If you haven't copied the udev rules provided in the repository to your local rules directory you need to run the program using sudo as it doesn't have access to the USB interface otherwise.

**Comment by akshit-sharma** [comment]
Thanks, its working now.
